
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "sicxe_fileleftNAMEleftCODOPleftREGleftATSHARPleftOR_GAND_GleftMORETLESSTMOREEQLESSEQleftPLUSMINUSleftMULTIPLYDIVIDEMODrightUMINUSFACTORIALADD ADDF ADDR AND AND_G ARROBA AT BASE BYTE CLEAR CODOP COMA COMF COMMENT_ML COMP COMPR C_TEXT DIRECTIV DIV DIVF DIVIDE DIVR END EQUALS FACTORIAL FINL FIX FLOAT FLOAT_NUM HEX_INT HIO INT J JEQ JGT JLT JSUB LDA LDB LDCH LDF LDL LDS LDT LDX LESSEQ LESST LPARENT LPS MINUS MOD MODIF MOREEQ MORET MUL MULF MULR MULTIPLY NAME NEWLINE NORM NUM OPERANDO OR OR_G PLUS RD REG RESB RESW RMO RPARENT RSUB SHARP SHIFTL SHIFTR SIO SSK STA START STB STCH STF STI STL STS STSW STT STX SUB SUBF SUBR SVC TD TIO TIX TIXR UMINUS WD WORD X_HEXsicxe_file : empty\n    | programa\n    | empty programa\n    | empty programa emptyprograma : inicio proposiciones fininicio : nombre_programa START numero NEWLINEinicio : nombre_programa START error NEWLINE inicio : error START numero NEWLINE numero : INT\n    | HEX_INTfin : END entrada entrada : NAMEproposiciones : proposiciones proposicion\n    | proposicionproposicion :\n    | directiva NEWLINE\n    | instruccion NEWLINE\n    | error NEWLINE\n    instruccion : etiqueta opformato\n    | opformato\n    \n    directiva : etiqueta tipodirectiva opdirectiva\n    | tipodirectiva opdirectivaopdirectiva : NUM\n    | NAME tipodirectiva : BYTE\n    | WORD\n    | RESB\n    | RESWetiqueta : NAME nombre_programa : NAME opformato : f4\n    | f3\n    | f2\n    | f1 f3 : simple3\n    | indirecto3\n    | inmediato3\n    | RSUB\n    | f3 : simple3 COMA 'X'f4 : PLUS f3simple3 : CODOP NAME\n    | CODOP NUMindirecto3 : CODOP AT NUM\n    | CODOP AT NAMEinmediato3 : CODOP SHARP NUM\n    | CODOP SHARP NAMEf2 : CODOP NUM\n    | CODOP REGf2 : CODOP REG COMA REG\n    | CODOP REG COMA NUMf1 : CODOP NEWLINE\n    empty : NEWLINE\n    |\n    "
    
_lr_action_items = {'NEWLINE':([0,5,9,10,11,12,13,14,15,17,18,23,24,25,26,27,28,29,30,31,32,36,37,39,40,41,43,44,45,46,47,50,51,52,53,56,57,58,59,60,61,62,63,64,65,67,68,69,70,71,72,73,74,75,],[4,-15,4,-15,-14,39,40,41,-39,-20,-29,-31,-32,-33,-34,-39,-35,-36,-37,-38,52,-5,-13,-16,-17,-18,-19,-22,-23,-24,-41,-43,-49,-52,-42,71,72,-9,-10,73,-11,-12,-21,-43,-40,-44,-45,-46,-47,-6,-7,-8,-50,-51,]),'error':([0,2,4,5,10,11,33,37,39,40,41,71,72,73,],[7,7,-53,14,14,-14,57,-13,-16,-17,-18,-6,-7,-8,]),'NAME':([0,2,4,5,10,11,16,19,20,21,22,32,37,38,39,40,41,42,48,54,55,71,72,73,],[8,8,-53,18,18,-14,46,-25,-26,-27,-28,53,-13,62,-16,-17,-18,46,53,68,70,-6,-7,-8,]),'$end':([0,1,2,3,4,9,35,36,61,62,],[-54,0,-1,-2,-53,-3,-4,-5,-11,-12,]),'END':([5,10,11,37,39,40,41,71,72,73,],[-15,38,-14,-13,-16,-17,-18,-6,-7,-8,]),'BYTE':([5,10,11,15,18,37,39,40,41,71,72,73,],[19,19,-14,19,-29,-13,-16,-17,-18,-6,-7,-8,]),'WORD':([5,10,11,15,18,37,39,40,41,71,72,73,],[20,20,-14,20,-29,-13,-16,-17,-18,-6,-7,-8,]),'RESB':([5,10,11,15,18,37,39,40,41,71,72,73,],[21,21,-14,21,-29,-13,-16,-17,-18,-6,-7,-8,]),'RESW':([5,10,11,15,18,37,39,40,41,71,72,73,],[22,22,-14,22,-29,-13,-16,-17,-18,-6,-7,-8,]),'PLUS':([5,10,11,15,18,37,39,40,41,71,72,73,],[27,27,-14,27,-29,-13,-16,-17,-18,-6,-7,-8,]),'RSUB':([5,10,11,15,18,27,37,39,40,41,71,72,73,],[31,31,-14,31,-29,31,-13,-16,-17,-18,-6,-7,-8,]),'CODOP':([5,10,11,15,18,27,37,39,40,41,71,72,73,],[32,32,-14,32,-29,48,-13,-16,-17,-18,-6,-7,-8,]),'START':([6,7,8,],[33,34,-30,]),'NUM':([16,19,20,21,22,32,42,48,54,55,66,],[45,-25,-26,-27,-28,50,45,64,67,69,75,]),'COMA':([28,50,51,53,64,],[49,-43,66,-42,-43,]),'REG':([32,66,],[51,74,]),'AT':([32,48,],[54,54,]),'SHARP':([32,48,],[55,55,]),'INT':([33,34,],[58,58,]),'HEX_INT':([33,34,],[59,59,]),'X':([49,],[65,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sicxe_file':([0,],[1,]),'empty':([0,9,],[2,35,]),'programa':([0,2,],[3,9,]),'inicio':([0,2,],[5,5,]),'nombre_programa':([0,2,],[6,6,]),'proposiciones':([5,],[10,]),'proposicion':([5,10,],[11,37,]),'directiva':([5,10,],[12,12,]),'instruccion':([5,10,],[13,13,]),'etiqueta':([5,10,],[15,15,]),'tipodirectiva':([5,10,15,],[16,16,42,]),'opformato':([5,10,15,],[17,17,43,]),'f4':([5,10,15,],[23,23,23,]),'f3':([5,10,15,27,],[24,24,24,47,]),'f2':([5,10,15,],[25,25,25,]),'f1':([5,10,15,],[26,26,26,]),'simple3':([5,10,15,27,],[28,28,28,28,]),'indirecto3':([5,10,15,27,],[29,29,29,29,]),'inmediato3':([5,10,15,27,],[30,30,30,30,]),'fin':([10,],[36,]),'opdirectiva':([16,42,],[44,63,]),'numero':([33,34,],[56,60,]),'entrada':([38,],[61,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sicxe_file","S'",1,None,None,None),
  ('sicxe_file -> empty','sicxe_file',1,'p_sicxe_file','lex_SICXE.py',421),
  ('sicxe_file -> programa','sicxe_file',1,'p_sicxe_file','lex_SICXE.py',422),
  ('sicxe_file -> empty programa','sicxe_file',2,'p_sicxe_file','lex_SICXE.py',423),
  ('sicxe_file -> empty programa empty','sicxe_file',3,'p_sicxe_file','lex_SICXE.py',424),
  ('programa -> inicio proposiciones fin','programa',3,'p_programa','lex_SICXE.py',428),
  ('inicio -> nombre_programa START numero NEWLINE','inicio',4,'p_inicio','lex_SICXE.py',434),
  ('inicio -> nombre_programa START error NEWLINE','inicio',4,'p_error_inicio_numero','lex_SICXE.py',439),
  ('inicio -> error START numero NEWLINE','inicio',4,'p_error_inicio_nombre_programa','lex_SICXE.py',444),
  ('numero -> INT','numero',1,'p_numero','lex_SICXE.py',449),
  ('numero -> HEX_INT','numero',1,'p_numero','lex_SICXE.py',450),
  ('fin -> END entrada','fin',2,'p_fin','lex_SICXE.py',455),
  ('entrada -> NAME','entrada',1,'p_entrada','lex_SICXE.py',460),
  ('proposiciones -> proposiciones proposicion','proposiciones',2,'p_proposiciones','lex_SICXE.py',465),
  ('proposiciones -> proposicion','proposiciones',1,'p_proposiciones','lex_SICXE.py',466),
  ('proposicion -> <empty>','proposicion',0,'p_proposicion','lex_SICXE.py',475),
  ('proposicion -> directiva NEWLINE','proposicion',2,'p_proposicion','lex_SICXE.py',476),
  ('proposicion -> instruccion NEWLINE','proposicion',2,'p_proposicion','lex_SICXE.py',477),
  ('proposicion -> error NEWLINE','proposicion',2,'p_proposicion','lex_SICXE.py',478),
  ('instruccion -> etiqueta opformato','instruccion',2,'p_instruccion','lex_SICXE.py',492),
  ('instruccion -> opformato','instruccion',1,'p_instruccion','lex_SICXE.py',493),
  ('directiva -> etiqueta tipodirectiva opdirectiva','directiva',3,'p_directiva','lex_SICXE.py',501),
  ('directiva -> tipodirectiva opdirectiva','directiva',2,'p_directiva','lex_SICXE.py',502),
  ('opdirectiva -> NUM','opdirectiva',1,'p_opdirectiva','lex_SICXE.py',509),
  ('opdirectiva -> NAME','opdirectiva',1,'p_opdirectiva','lex_SICXE.py',510),
  ('tipodirectiva -> BYTE','tipodirectiva',1,'p_tipodirectiva','lex_SICXE.py',517),
  ('tipodirectiva -> WORD','tipodirectiva',1,'p_tipodirectiva','lex_SICXE.py',518),
  ('tipodirectiva -> RESB','tipodirectiva',1,'p_tipodirectiva','lex_SICXE.py',519),
  ('tipodirectiva -> RESW','tipodirectiva',1,'p_tipodirectiva','lex_SICXE.py',520),
  ('etiqueta -> NAME','etiqueta',1,'p_etiqueta','lex_SICXE.py',527),
  ('nombre_programa -> NAME','nombre_programa',1,'p_nombre_programa','lex_SICXE.py',534),
  ('opformato -> f4','opformato',1,'p_opformato','lex_SICXE.py',541),
  ('opformato -> f3','opformato',1,'p_opformato','lex_SICXE.py',542),
  ('opformato -> f2','opformato',1,'p_opformato','lex_SICXE.py',543),
  ('opformato -> f1','opformato',1,'p_opformato','lex_SICXE.py',544),
  ('f3 -> simple3','f3',1,'p_f3','lex_SICXE.py',551),
  ('f3 -> indirecto3','f3',1,'p_f3','lex_SICXE.py',552),
  ('f3 -> inmediato3','f3',1,'p_f3','lex_SICXE.py',553),
  ('f3 -> RSUB','f3',1,'p_f3','lex_SICXE.py',554),
  ('f3 -> <empty>','f3',0,'p_f3','lex_SICXE.py',555),
  ('f3 -> simple3 COMA X','f3',3,'p_f3_Indexado','lex_SICXE.py',564),
  ('f4 -> PLUS f3','f4',2,'p_f4','lex_SICXE.py',571),
  ('simple3 -> CODOP NAME','simple3',2,'p_simple3','lex_SICXE.py',578),
  ('simple3 -> CODOP NUM','simple3',2,'p_simple3','lex_SICXE.py',579),
  ('indirecto3 -> CODOP AT NUM','indirecto3',3,'p_indirecto3','lex_SICXE.py',586),
  ('indirecto3 -> CODOP AT NAME','indirecto3',3,'p_indirecto3','lex_SICXE.py',587),
  ('inmediato3 -> CODOP SHARP NUM','inmediato3',3,'p_inmediato3','lex_SICXE.py',594),
  ('inmediato3 -> CODOP SHARP NAME','inmediato3',3,'p_inmediato3','lex_SICXE.py',595),
  ('f2 -> CODOP NUM','f2',2,'p_f2','lex_SICXE.py',602),
  ('f2 -> CODOP REG','f2',2,'p_f2','lex_SICXE.py',603),
  ('f2 -> CODOP REG COMA REG','f2',4,'p_f2_3','lex_SICXE.py',610),
  ('f2 -> CODOP REG COMA NUM','f2',4,'p_f2_3','lex_SICXE.py',611),
  ('f1 -> CODOP NEWLINE','f1',2,'p_f1','lex_SICXE.py',616),
  ('empty -> NEWLINE','empty',1,'p_empty','lex_SICXE.py',624),
  ('empty -> <empty>','empty',0,'p_empty','lex_SICXE.py',625),
]
